services:
  - type: web
    name: n8n-v2.8.3
    env: docker
    image: n8nio/n8n:2.8.3
    plan: standard
    port: 5678
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-chatbot-6q3s.onrender.com/
      - key: DB_TYPE
        value: sqlite
      - key: DB_SQLITE_DATABASE
        value: /home/node/.n8n/database.sqlite
      - key: N8N_USER_FOLDER
        value: /home/node/.n8n
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok
    disks:
      - name: n8n-data
        mountPath: /home/node/.n8n
        sizeGB: 1
