services:
  - type: web
    name: n8n-v2.8.3
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    port: 5678
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production